name: AWS Terraform Ansible

on:
  workflow_dispatch:

jobs:

  # ==========================================
  # JOB 1 - AWS CONNECTION TEST
  # ==========================================
  aws-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Check AWS connection
        run: |
          aws sts get-caller-identity


  # ==========================================
  # JOB 2 - TERRAFORM
  # ==========================================
  terraform:
    needs: aws-connection
    runs-on: ubuntu-latest

    # Pass EC2 IP to the next job
    outputs:
      ec2_ip: ${{ steps.get_ip.outputs.ec2_ip }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Get EC2 public IP
      - name: Get EC2 IP
        id: get_ip
        run: |
          echo "ec2_ip=$(terraform output -raw ec2_public_ip)" >> "$GITHUB_OUTPUT"


  # ==========================================
  # JOB 3 - ANSIBLE
  # ==========================================
  ansible:
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Ansible
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      # Check Ansible version
      - name: Check Ansible version
        run: |
          ansible --version

      # Create SSH private key from GitHub Secret
      - name: Create SSH private key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ec2-key.pem
          chmod 400 ec2-key.pem

      # Create dynamic Ansible inventory
      - name: Create Ansible inventory
        run: |
          cat > inventory.ini <<EOF
          [web]
          ${{ needs.terraform.outputs.ec2_ip }} ansible_user=ec2-user ansible_ssh_private_key_file=./ec2-key.pem
          EOF

      # Display inventory
      - name: Show inventory
        run: |
          cat inventory.ini

      # Test SSH connection using Ansible
      - name: Test Ansible connection
        run: |
          ansible web -i inventory.ini -m ping
