name: Secret Demo 

on: 
  workflow_dispatch: 
  push: 
  
  
jobs: 
  secret-demo: 
    runs-on: ubuntu-latest
	  steps: 
	    - name: Read Secret
        env: 
          DEMO_SECRET: ${{ secrets.DEMO_SECRET }}
        run: |
          echo "$DEMO_SECRET"
          echo "${#DEMO_SECRET}"
  
